services:
  # Backend API Service
  - type: web
    name: crickarena-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        sync: false  # Will be set after frontend deployment
      - key: MONGO_URI
        sync: false  # Must be set in Render dashboard for security
      # Firebase Admin credentials (set in Render dashboard)
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      # Razorpay credentials (set in Render dashboard)
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

  # Frontend Static Site
  - type: static_site
    name: crickarena-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        sync: false  # Will be set after backend deployment
      # Firebase Web App Config (can be set here or in Render dashboard)
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
    routes:
      # Vue Router History Mode support
      - type: rewrite
        source: /*
        destination: /index.html