services:
  # Backend API Service
  - type: web
    name: crickarena-backend
    runtime: node
    rootDir: backend
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      # Add these environment variables with your actual values
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
    healthCheckPath: /health

  # Frontend Static Site
  - type: static_site
    name: crickarena-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    region: oregon
    envVars:
      - key: VITE_API_BASE
        value: https://crickarena-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html